// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YP_GxNyCv2W4rwy9saf0ZMJ0eD_M9bs',
    appId: '1:120016097465:web:a2a9345891fab1453c8b68',
    messagingSenderId: '120016097465',
    projectId: 'betplus-87c82',
    authDomain: 'betplus-87c82.firebaseapp.com',
    storageBucket: 'betplus-87c82.appspot.com',
    measurementId: 'G-7TF1EKY15Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0lPtgZwLgLuAjVZcx-nCTWmDUoZPHiug',
    appId: '1:120016097465:android:bb706b9edcf0c69a3c8b68',
    messagingSenderId: '120016097465',
    projectId: 'betplus-87c82',
    storageBucket: 'betplus-87c82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWsu3R7-44eUdEGf3xnLAr4ZOD-Jl2Vwo',
    appId: '1:120016097465:ios:bb737df3812784ed3c8b68',
    messagingSenderId: '120016097465',
    projectId: 'betplus-87c82',
    storageBucket: 'betplus-87c82.appspot.com',
    iosBundleId: 'com.beelogical.betplus01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWsu3R7-44eUdEGf3xnLAr4ZOD-Jl2Vwo',
    appId: '1:120016097465:ios:5e5612bc3f6071803c8b68',
    messagingSenderId: '120016097465',
    projectId: 'betplus-87c82',
    storageBucket: 'betplus-87c82.appspot.com',
    iosBundleId: 'com.example.betplusIos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6YP_GxNyCv2W4rwy9saf0ZMJ0eD_M9bs',
    appId: '1:120016097465:web:3e0ae99620ae92e53c8b68',
    messagingSenderId: '120016097465',
    projectId: 'betplus-87c82',
    authDomain: 'betplus-87c82.firebaseapp.com',
    storageBucket: 'betplus-87c82.appspot.com',
    measurementId: 'G-WYN8Y1SDQF',
  );
}
